version : '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WINDOW_SIZE=60
      - MAX_REQUESTS=100
  redis:
    image: redis:6.2
    ports :
      - "6379:6379"
